name: Deploy Front-end to GitHub Pages

on:
  push:
    branches:
      - main # Dispara o deploy sempre que houver push na main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar o Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Instalar Dependências
        run: bun install
        working-directory: ./client # 👈 Entra na pasta client para instalar

      - name: Rodar o Build do Vite
        run: bun run build
        working-directory: ./client # 👈 Ent─ra na pasta client para compilar

      - name: Configurar Páginas
        uses: actions/configure-pages@v4

      - name: Upload do Artefato Correto
        uses: actions/upload-pages-artifact@v3
        with:
          path: './client/dist' # 👈 Alvo certeiro na pasta dist gerada dentro de client

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4